### ISSUE TITLE
React 15 Warning: Unknown prop `placeholderChar` on <input> tag.

### ISSUE THREAD

**Issue by dbrans** [insin/react-maskedinput#61] opened 2016-07-15 01:21 UTC
Remove this prop from the element. For details, see https://fb.me/react-unknown-prop.

**Comment by basham** [comment] 2016-07-20 19:26
#59 provided this fix, and it was released as `v3.2.1`. However, the compiled npm build of `v3.2.1` in `./lib/index.js` didn't pick up the change. It looks like:

``` js
  render: function render() {
    var _this = this;

    var _props = this.props;
    var mask = _props.mask;
    var formatCharacters = _props.formatCharacters;
    var size = _props.size;
    var placeholder = _props.placeholder;

    var props = _objectWithoutProperties(_props, ['mask', 'formatCharacters', 'size', 'placeholder']);

    var patternLength = this.mask.pattern.length;
    return React.createElement('input', _extends({}, props, {
      ref: function (r) {
        return _this.input = r;
      },
      maxLength: patternLength,
      onChange: this._onChange,
      onKeyDown: this._onKeyDown,
      onKeyPress: this._onKeyPress,
      onPaste: this._onPaste,
      placeholder: placeholder || this.mask.emptyValue,
      size: size || patternLength,
      value: this._getDisplayValue()
    }));
  }
```

**Comment by dbrans** [comment] 2016-07-20 20:15
+1

**Comment by iamdustan** [comment] 2016-08-09 15:29
rebuilt and republished. Apologies.

**Closed as completed by iamdustan** 2016-08-09 15:29 UTC

**Comment by bjornd** [comment] 2016-12-09 15:39
It reproduces again in 3.3.2

**Comment by leordev** [comment] 2017-02-07 04:05
I'm having this on 3.3.3, should I update?
